

environment:
 access_token:
    secure: OhG0TwIHs1lyUJxOHe/w8f6wM0jva9oYkfrTzMdOoDXhhtmLtIJcmeLTcjdkDOXE

install:
- node --version
- npm --version
- npm install
- npm install hexo-cli -g
build_script:
- hexo generate


artifacts:
- path: public
on_success:
- git config --global credential.helper store
- ps: Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:access_token):x-oauth-basic@github.com`n"
- git config --global user.email "%GIT_USER_EMAIL%"
- git config --global user.name "%GIT_USER_NAME%"
- cd %APPVEYOR_BUILD_FOLDER%\public
- git add .
- git commit -m "Update docs"
- git push --force --quiet https://github.com/ycg31/ycg31.github.io.git master:master
- appveyor AddMessage "Static Site Updated"
